### ISSUE TITLE
Impossibilité de modifier ou sélectionner un composant dans une card

### ISSUE THREAD

**Issue by KennethPadonou0** [metayoub/qodly-grid-layout#3]
Bug rencontré avec le composant grid layout (version 0.1.0) : 
- Lorsque j'insère un composant dans une card grid layout, je n'ai plus la possibilité de saisir ou modifier le composant insérer.

**Comment by metayoub** [comment]
this bug has been fixed in https://github.com/metayoub/qodly-grid-layout/pull/4

**Comment by metayoub** [comment]
@KennethPadonou0 plz download V0.2.0
